from __future__ import annotations

from content_agent.intelligence.luna_client import LunaClient
from content_agent.models.schemas import Candidate

_FILMING = {"type": "object", "additionalProperties": False, "properties": {"format": {"type": "string"}, "camera": {"type": "string"}, "location": {"type": "string"}, "lighting": {"type": "string"}, "props": {"type": "array", "items": {"type": "string"}}, "screen_recordings_needed": {"type": "array", "items": {"type": "string"}}}, "required": ["format", "camera", "location", "lighting", "props", "screen_recordings_needed"]}
_EDITING = {"type": "object", "additionalProperties": False, "properties": {"pace": {"type": "string"}, "cuts": {"type": "string"}, "zoom": {"type": "string"}, "captions": {"type": "string"}, "music": {"type": "string"}, "sound_effects": {"type": "array", "items": {"type": "string"}}}, "required": ["pace", "cuts", "zoom", "captions", "music", "sound_effects"]}
_SOURCE = {"type": "object", "additionalProperties": False, "properties": {"url": {"type": "string"}, "creator": {"type": "string"}, "views": {"type": ["integer", "null"]}, "followers": {"type": ["integer", "null"]}, "viral_ratio": {"type": ["number", "null"]}}, "required": ["url", "creator", "views", "followers", "viral_ratio"]}
_ADAPTATION_SCHEMA = {"type": "object", "additionalProperties": False, "properties": {"internal_title": {"type": "string"}, "source": _SOURCE, "why_selected": {"type": "string"}, "source_pattern": {"type": "string"}, "angellos_angle": {"type": "string"}, "content_goal": {"type": "string"}, "hook": {"type": "string"}, "script": {"type": "object", "additionalProperties": False, "properties": {"hook": {"type": "string"}, "development": {"type": "array", "items": {"type": "string"}}, "cta": {"type": "string"}}, "required": ["hook", "development", "cta"]}, "shot_list": {"type": "array", "items": {"type": "object", "additionalProperties": False, "properties": {"start": {"type": "number"}, "end": {"type": "number"}, "shot": {"type": "string"}, "spoken": {"type": "string"}, "on_screen_text": {"type": "string"}, "b_roll": {"type": "string"}, "editing": {"type": "string"}}, "required": ["start", "end", "shot", "spoken", "on_screen_text", "b_roll", "editing"]}}, "filming": _FILMING, "editing": _EDITING, "target_duration_seconds": {"type": "integer"}, "caption": {"type": "string"}, "cta": {"type": "string"}, "content_type": {"type": "string"}, "ig_content_type": {"type": "string"}, "why_test_this": {"type": "string"}, "facts_that_must_be_verified_before_filming": {"type": "array", "items": {"type": "string"}}}, "required": ["internal_title", "source", "why_selected", "source_pattern", "angellos_angle", "content_goal", "hook", "script", "shot_list", "filming", "editing", "target_duration_seconds", "caption", "cta", "content_type", "ig_content_type", "why_test_this", "facts_that_must_be_verified_before_filming"]}
_QUALITY_SCHEMA = {"type": "object", "additionalProperties": False, "properties": {"approved": {"type": "boolean"}, "issues": {"type": "array", "items": {"type": "string"}}}, "required": ["approved", "issues"]}


async def adapt_to_angellos(client: LunaClient, candidate: Candidate, gemini: dict, context: str, recent_content: list[dict], historical_signals: dict, language: str) -> dict:
    prompt = f"Create an original, production-ready Angellos Reel brief in {language}. Source metadata: {candidate.to_dict()}\nGemini observations: {gemini}\nCanonical context: {context}\nRecent content: {recent_content[:20]}\nHistorical signals: {historical_signals}\nAbstract the mechanism. Never translate/copy the source script, caption, anecdote, visual identity, testimonial, feature, outcome, or statistic. Mark unknown facts for verification."
    adaptation = await client.json("You are Luna. Create only factually grounded original marketing concepts that a founder can film today.", prompt, _ADAPTATION_SCHEMA)
    # Source evidence is deterministic input, not model-generated marketing copy.
    adaptation["source"] = {"url": candidate.source_url, "creator": candidate.creator_username, "views": candidate.views, "followers": candidate.followers, "viral_ratio": candidate.viral_ratio}
    return adaptation


async def quality_check(client: LunaClient, adaptation: dict, context: str, recent_content: list[dict]) -> dict:
    return await client.json("You are Luna's final quality gate. Approve only if original, factually safe, non-repetitive, clear, filmable and CTA-coherent.", f"Adaptation: {adaptation}\nContext: {context}\nRecent: {recent_content[:20]}", _QUALITY_SCHEMA)
