"""
Fetches Angellos brand context from Notion:
- Product vision, avatar, positioning (NOTION_ANGELLOS_CONTEXT_DB)
- Beta conversations, results, objections (NOTION_ANGELLOS_RESULTS_DB)
- Topics covered in the last 30 days (NOTION_DATABASE_ID — generated scripts)
- Performance patterns from performance_patterns.json (generated by sync-my-stats)

Used to enrich the Claude prompt with real Angellos vocabulary, positioning,
and avoid repeating recent topics.
"""
import json
import os
from datetime import datetime, timezone, timedelta
from notion_client import Client
from config import NOTION_API_KEY, NOTION_ANGELLOS_CONTEXT_DB, NOTION_ANGELLOS_RESULTS_DB, NOTION_DATABASE_ID
from utils.logger import log_info, log_success, log_error

_PATTERNS_FILE = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "performance_patterns.json")
)

_notion = Client(auth=NOTION_API_KEY)

_CONTEXT_CHARS = 800
_RESULTS_CHARS = 600


def fetch_angellos_context() -> str:
    """
    Returns a context string ready to inject into the Claude prompt.
    Combines product/avatar context + beta results.
    """
    log_info("Fetching Angellos context from Notion (product vision + beta results)...")
    parts = []

    context = _fetch_product_context()
    if context:
        parts.append("## Angellos — Product vision & ICP\n" + context)

    results = _fetch_beta_results()
    if results:
        parts.append("## Beta conversations, results & objections\n" + results)

    if not parts:
        log_error("No Notion context fetched — check integration access.")
        return ""

    log_success(f"Angellos Notion context loaded ({len(' '.join(parts))} chars)")
    return "\n\n".join(parts)


def _fetch_product_context() -> str:
    if not NOTION_ANGELLOS_CONTEXT_DB:
        return ""
    try:
        response = _notion.databases.query(
            database_id=NOTION_ANGELLOS_CONTEXT_DB,
            page_size=10,
        )
    except Exception as e:
        log_error(f"Product context DB: {e}")
        return ""

    excerpts = []
    for page in response.get("results", []):
        title = _title_of(page)
        content = _page_text(page["id"], max_chars=_CONTEXT_CHARS)
        if content:
            excerpts.append(f"**{title}**\n{content}")

    return "\n\n---\n\n".join(excerpts)


def _fetch_beta_results() -> str:
    if not NOTION_ANGELLOS_RESULTS_DB:
        return ""
    try:
        response = _notion.databases.query(
            database_id=NOTION_ANGELLOS_RESULTS_DB,
            page_size=10,
        )
    except Exception as e:
        log_error(f"Beta results DB: {e}")
        return ""

    excerpts = []
    for page in response.get("results", []):
        title = _title_of(page)
        content = _page_text(page["id"], max_chars=_RESULTS_CHARS)
        if content:
            excerpts.append(f"**{title}**\n{content}")

    return "\n\n---\n\n".join(excerpts)


def _page_text(page_id: str, max_chars: int = 800) -> str:
    try:
        blocks = _notion.blocks.children.list(block_id=page_id, page_size=20)
    except Exception:
        return ""

    lines = []
    total = 0
    for block in blocks.get("results", []):
        text = _block_text(block)
        if text:
            lines.append(text)
            total += len(text)
            if total >= max_chars:
                break

    return " ".join(lines)[:max_chars]


def _block_text(block: dict) -> str:
    btype = block.get("type", "")
    content = block.get(btype, {})
    rich_texts = content.get("rich_text", [])
    return "".join(rt.get("plain_text", "") for rt in rich_texts)


def fetch_performance_patterns() -> str:
    """
    Reads performance_patterns.json (generated by sync-my-stats + Claude).
    Falls back to Notion query if absent.
    Returns a text block ready to inject into the Claude prompt.
    """
    if os.path.exists(_PATTERNS_FILE):
        try:
            with open(_PATTERNS_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
            if data:
                return _format_patterns_from_json(data)
        except Exception as e:
            log_error(f"Reading performance_patterns.json: {e}")

    log_info("performance_patterns.json missing — fallback to Notion")
    return _fetch_patterns_from_notion()


def _format_patterns_from_json(data: dict) -> str:
    n = data.get("total_reels", 0)
    avg_views = data.get("avg_views", 0)
    avg_likes = data.get("avg_likes", 0)
    generated = data.get("generated_at", "")

    lines = [
        f"**{n} Reels @angellos.ai analyzed** (data from {generated}):",
        f"Average: {avg_views:,} views · {avg_likes:,} likes",
        "",
    ]

    top = data.get("top_performers", [])
    if top:
        lines.append("**Top performers:**")
        for i, p in enumerate(top[:5], 1):
            line = f"{i}. {p.get('titre', '')[:50]} — {p.get('vues', 0):,} views"
            if p.get("hook"):
                line += f"\n   Hook: « {p['hook'][:80]} »"
            lines.append(line)
        lines.append("")

    patterns = data.get("patterns", {})
    if patterns.get("hooks_gagnants"):
        lines.append("**Hooks that generate the most views:**")
        lines += [f"- {h}" for h in patterns["hooks_gagnants"][:5]]
        lines.append("")

    if patterns.get("sujets_performants"):
        lines.append("**Best-performing topics/themes:**")
        lines += [f"- {s}" for s in patterns["sujets_performants"][:5]]
        lines.append("")

    if patterns.get("formule_gagnante"):
        lines.append(f"**Winning formula:** {patterns['formule_gagnante']}")
        lines.append("")

    insights = data.get("insights", [])
    if insights:
        lines.append("**Actionable insights:**")
        lines += [f"- {ins}" for ins in insights[:3]]
        lines.append("")

    lines += [
        "**Apply to the next script:**",
        "Identify which hook types, topics, and formats drive the most views.",
        "Apply these winning patterns. Favor short punchy hooks and topics around DM overload,",
        "missed deals, and automation that closes high-ticket.",
    ]

    log_success(f"Patterns loaded from performance_patterns.json ({n} reels)")
    return "\n".join(lines)


def _fetch_patterns_from_notion() -> str:
    if not NOTION_DATABASE_ID:
        return ""
    try:
        resp = _notion.databases.query(
            database_id=NOTION_DATABASE_ID,
            filter={"property": "Vues IG", "number": {"is_not_empty": True}},
            sorts=[{"property": "Vues IG", "direction": "descending"}],
            page_size=50,
        )
    except Exception as e:
        log_error(f"Performance patterns Notion: {e}")
        return ""

    pages = resp.get("results", [])
    if not pages:
        return ""

    performers = []
    for page in pages:
        props = page.get("properties", {})
        views = (props.get("Vues IG") or {}).get("number") or 0
        saves = (props.get("Saves IG") or {}).get("number") or 0
        likes = (props.get("Likes IG") or {}).get("number") or 0
        hook_rts = (props.get("Hook analysé") or {}).get("rich_text", [])
        hook = "".join(rt.get("plain_text", "") for rt in hook_rts)[:100]
        if views > 0:
            performers.append({"title": _title_of(page), "views": views,
                                "saves": saves, "likes": likes, "hook": hook})

    if not performers:
        return ""

    n = len(performers)
    avg_views = sum(p["views"] for p in performers) // n
    avg_saves = sum(p["saves"] for p in performers) // n
    top5 = performers[:5]

    lines = [
        f"**{n} Angellos Reels with IG stats:**",
        f"Average: {avg_views:,} views · {avg_saves:,} saves",
        "",
        "**Top performers:**",
    ]
    for i, p in enumerate(top5, 1):
        line = f"{i}. {p['title']} — {p['views']:,} views · {p['saves']:,} saves"
        if p["hook"]:
            line += f"\n   Hook: « {p['hook']} »"
        lines.append(line)

    lines += [
        "",
        "**Apply:** identify and replicate the winning patterns (short hooks, DM pain points, automation results).",
    ]

    log_success(f"Notion patterns loaded ({n} posts)")
    return "\n".join(lines)


def fetch_recent_topics(days: int = 30) -> str:
    """
    Queries the scripts database and returns titles of scripts
    generated in the last N days, ready to inject into the prompt.
    Returns empty string if no results or on error.
    """
    if not NOTION_DATABASE_ID:
        return ""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    try:
        response = _notion.databases.query(
            database_id=NOTION_DATABASE_ID,
            filter={
                "timestamp": "created_time",
                "created_time": {"on_or_after": cutoff},
            },
            sorts=[{"timestamp": "created_time", "direction": "descending"}],
        )
    except Exception as e:
        log_error(f"Recent topics Notion: {e}")
        return ""

    lines = []
    for page in response.get("results", []):
        title = _title_of(page)
        created = page.get("created_time", "")[:10]
        if title:
            lines.append(f"- {title} ({created})")

    log_info(f"{len(lines)} recent topic(s) fetched from Notion")
    return "\n".join(lines)


def _title_of(page: dict) -> str:
    for prop in page.get("properties", {}).values():
        if prop.get("type") == "title":
            parts = prop.get("title", [])
            return "".join(p.get("plain_text", "") for p in parts)
    return ""
